---
##################################################################
# This play performs Eventing Configuration for Poweredge      #
##################################################################

- name: Eventing-Configuration
  ansible.builtin.include_role:
    name: proautomate_poweredge
    tasks_from: poweredge_eventing
  when:
    - idrac_config.eventing.eventing_settings is defined
