---
- name: View all volume details
  dellemc.openmanage.dellemc_idrac_storage_volume:
    idrac_ip: "{{ array_ip }}"
    validate_certs: "{{ verifycert }}"
    idrac_user: "{{ user }}"
    idrac_password: "{{ password }}"
    state: "view"
  register: storage_details

- name: Print the all storage details
  ansible.builtin.debug:
    msg: "{{ storage_details }}"
