---
- name: Import Eventing configurations
  ansible.builtin.set_fact:
    eventing_configs: "{{ idrac_config.eventing.eventing_settings }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ array_ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ user }}"
      idrac_password: "{{ password }}"
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ eventing_configs }}"
  no_log: true

- name: Eventing settings for idrac
  dellemc.openmanage.idrac_attributes: "{{ item }}"
  loop: "{{ fs_items }}"
  register: eventingconfig

- name: Display the eventing settings result
  ansible.builtin.debug:
    msg: "{{ eventingconfig }}"
