---
- name: Set the array ip
  ansible.builtin.set_fact:
    array_ip: "{{item.ip}}"
    user: "{{item.user}}"
    password: "{{item.password}}"
  loop: "{{idrac}}"
  when: item.ip == "{{idrac_config.idrac_ip}}" 

- name: Import powerconfig configurations
  ansible.builtin.set_fact:
    power_configs: "{{ idrac_config.power.power_state }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      baseuri: "{{ array_ip }}"
      validate_certs: "{{ verifycert }}"
      username: "{{ user }}"
      password: "{{ password }}"
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ power_configs }}"
  no_log: true

- name: Power on the idrac
  dellemc.openmanage.redfish_powerstate: "{{ item }}"
  loop: "{{ fs_items }}"
  register: power_result

- name: display the result
  ansible.builtin.debug:
    msg: "{{ power_result }}"

- name: Pause for 5 seconds before running again
  ansible.builtin.pause:
    seconds: 5     
