---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"

- name: Import network configurations
  ansible.builtin.set_fact:
    network_configs: "{{ idrac_config.network.network_settings }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ item.ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ item.user }}"
      idrac_password: "{{ item.password }}"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"      
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ network_configs }}"
  no_log: true

- name: Configure Network Settings for idrac
  dellemc.openmanage.idrac_network: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 12
  register: networkconfig

- name: display the result
  ansible.builtin.debug:
    msg: "{{ networkconfig }}"

- name: Pause for 5 seconds before running again
  ansible.builtin.pause:
    seconds: 5   