---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"

- name: Import virtual disk create configurations
  ansible.builtin.set_fact:
    storage_configs: "{{ idrac_config.storagevolume.storagevolume_config }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      baseuri: "{{ item.ip }}"
      #validate_certs: "{{ verifycert }}"
      username: "{{ item.user }}"
      password: "{{ item.password }}"
      state: "present"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"     
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ storage_configs }}"

- name: Create virtual disk
  dellemc.openmanage.redfish_storage_volume: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 10
  register: create_vdisk

- name: Display result
  ansible.builtin.debug:
    msg: "{{ create_vdisk }}"

   
