---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"

- name: Import storage configurations
  ansible.builtin.set_fact:
    storage_configs: "{{ idrac_config.storage.storage_config }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      baseuri: "{{ item.ip }}"
      validate_certs: "{{ verifycert }}"
      username: "{{ item.user }}"
      password: "{{ item.password }}"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"     
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ storage_configs }}"
  no_log: true

- name: Configure Storage Settings for idrac
  dellemc.openmanage.idrac_redfish_storage_controller: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 10
  register: storageconfigres

- name: display
  ansible.builtin.debug:
    msg: "{{ storageconfigres }}"


