---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"
 

- name: Import firmware update configurations
  ansible.builtin.set_fact:
    firmware_configs: "{{ idrac_config.firmware.firmware_update }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ item.ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ item.user }}"
      idrac_password: "{{ item.password }}"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"    
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ firmware_configs }}"
  no_log: true

- name: firware update for idrac
  dellemc.openmanage.idrac_firmware: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 10
  register: firmwareconfig

- name: display the firware update result
  ansible.builtin.debug:
    msg: "{{ firmwareconfig }}"

   
