---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"

- name: Import os deploy configurations
  ansible.builtin.set_fact:
    osdeploy_configs: "{{ idrac_config.OSdeploy.OSdeploy_config }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ item.ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ item.user }}"
      idrac_password: "{{ item.password }}"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"      
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ osdeploy_configs }}"
  no_log: true

- name: Deploy OS -boot to a network device
  dellemc.openmanage.idrac_os_deployment: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 10
  register: os_deploy_result

- name: display the result
  ansible.builtin.debug:
    msg: "{{ os_deploy_result }}"

    
