---
- name: Import bios configurations
  ansible.builtin.set_fact:
    bios_configs: "{{ idrac_config.bios.bios_settings }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ array_ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ user }}"
      idrac_password: "{{ password }}"
    no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ bios_configs }}"
  no_log: true

- name: Configure Bios Settings for idrac
  dellemc.openmanage.idrac_bios: "{{ item }}"
  loop: "{{ fs_items }}"
  register: bios

- name: display the bios configuration result
  ansible.builtin.debug:
    msg: "{{ bios }}"
