---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"

- name: Get Firmware System Inventory
  dellemc.openmanage.idrac_firmware_info:
    idrac_ip: "{{ array_ip }}"
    validate_certs: "{{ verifycert }}"
    idrac_user: "{{ item.user }}"
    idrac_password: "{{ item.password }}"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"     
  register: firmware_details
  no_log: true
  
- name: Display Firware Inventory details
  ansible.builtin.debug:
    msg: "{{ firmware_details }}"
