---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"
    
- name: Import user create configurations
  ansible.builtin.set_fact:
    user_configs: "{{ idrac_config.user.users }}"  

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ item.ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ item.user }}"
      idrac_password: "{{ item.password }}"
      state: "present"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"  
  no_log: true 
      
- debug:
    msg: 
    - "{{idrac_base.idrac_ip}}"
    - "{{idrac_base.idrac_user}}"
    - "{{idrac_base.idrac_password}}"


- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ user_configs }}"
  no_log: true

- name: Create User for idrac
  dellemc.openmanage.idrac_user: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 10
  register: user_create

- name: display
  ansible.builtin.debug:
    msg: "{{ user_create }}"

