---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"

- name: Import boot configurations
  ansible.builtin.set_fact:
    boot_configs: "{{ idrac_config.boot.boot_settings }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ item.ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ item.user }}"
      idrac_password: "{{ item.password }}"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"   
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ boot_configs}}"
  no_log: true

- name: Configure Boot Settings for idrac
  dellemc.openmanage.idrac_bios: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 10
  register: boot

- name: display the boot configuration result
  ansible.builtin.debug:
    msg: "{{ boot }}"

    
