---
- name: Set the array ip
  ansible.builtin.set_fact:
    array_ip: "{{item.ip}}"
    user: "{{item.user}}"
    password: "{{item.password}}"
  loop: "{{idrac}}"
  when: item.ip == "{{idrac_config.idrac_ip}}" 

- name: Import network configurations
  ansible.builtin.set_fact:
    network_configs: "{{ idrac_config.network.network_settings }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ array_ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ user }}"
      idrac_password: "{{ password }}"
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ network_configs }}"
  no_log: true

- name: Configure Network Settings for idrac
  dellemc.openmanage.idrac_network: "{{ item }}"
  loop: "{{ fs_items }}"
  register: networkconfig

- name: display the result
  ansible.builtin.debug:
    msg: "{{ networkconfig }}"
