---
- name: Set the array ip
  ansible.builtin.set_fact:
    array_ip: "{{item.ip}}"
    user: "{{item.user}}"
    password: "{{item.password}}"
  loop: "{{idrac}}"
  when: item.ip == "{{idrac_config.idrac_ip}}" 

- name: Import storage configurations
  ansible.builtin.set_fact:
    storage_configs: "{{ idrac_config.storage.storage_config }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      baseuri: "{{ array_ip }}"
      validate_certs: "{{ verifycert }}"
      username: "{{ user }}"
      password: "{{ password }}"
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ storage_configs }}"
  no_log: true

- name: Configure Storage Settings for idrac
  dellemc.openmanage.idrac_redfish_storage_controller: "{{ item }}"
  loop: "{{ fs_items }}"
  register: storageconfigres

- name: display
  ansible.builtin.debug:
    msg: "{{ storageconfigres }}"
