---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"

- name: Import virtual disk delete configurations
  ansible.builtin.set_fact:
    storage_configs: "{{ idrac_config.storagevolume.storagevolume_config }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ item.ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ item.user }}"
      idrac_password: "{{ item.password }}"
      state: "delete"
  when: temp_ip == item.ip 
  loop: "{{idrac}}"     
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ storage_configs }}"
  no_log: true

- name: Delete virtual disk
  dellemc.openmanage.dellemc_idrac_storage_volume: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 10
  register: delete_vdisk

- name: Display result
  ansible.builtin.debug:
    msg: "{{ delete_vdisk }}"


