---
- name: Import user delete configurations
  ansible.builtin.set_fact:
    user_configs: "{{ idrac_config.user.users }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ array_ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ user }}"
      idrac_password: "{{ password }}"
      state: "absent"
  no_log: true

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ user_configs }}"
  no_log: true

- name: Delete User for idrac
  dellemc.openmanage.idrac_user: "{{ item }}"
  loop: "{{ fs_items }}"
  register: user_delete

- name: display
  ansible.builtin.debug:
    msg: "{{ user_delete }}"

