---
- name: Import user update configurations
  ansible.builtin.set_fact:
    user_configs: "{{ idrac_config.user.users }}"

- name: Set base module configuration
  ansible.builtin.set_fact:
    idrac_base:
      idrac_ip: "{{ item.ip }}"
      validate_certs: "{{ verifycert }}"
      idrac_user: "{{ item.user }}"
      idrac_password: "{{ item.password }}"
      state: "present"
  when: temp_ip == item.ip 
  loop: "{{idrac}}" 
  no_log: true    
 

- name: Combine configurations
  ansible.builtin.set_fact:
    fs_items: "{{ (fs_items | default([])) + [ item | combine(idrac_base) ] }}"
  loop: "{{ user_configs }}"
  no_log: true

- name: Update User for idrac
  dellemc.openmanage.idrac_user: "{{ item }}"
  loop: "{{ fs_items }}"
  loop_control:
    pause: 10
  register: user_update

- name: display
  ansible.builtin.debug:
    msg: "{{ user_update }}"

  
