---
- name: Printing ip selected from 1st request
  debug:
    var: array_ip
    
- name: setting fact for comparision
  set_fact:
    temp_ip: "{{ array_ip }}"

- name: get all nic mac addresses
  ansible.builtin.uri:
     url: "https://{{item.ip}}/redfish/v1/Systems/System.Embedded.1/EthernetInterfaces"
     #https://{{item.ip}}/redfish/v1/Systems/System.Embedded.1/EthernetInterfacesorNetworkAdapters
     user: "{{ item.user }}"
     password: "{{ item.password }}"
     method: "GET"
     status_code: 200
     validate_certs: false
     force_basic_auth: true
     headers:
        Accept: "application/json"
  when: temp_ip == item.ip 
  loop: "{{idrac}}" 
  no_log: true      
  register: nic_address

- debug:
    msg: "{{nic_address}}"   

- name: Ethernet Interfaces   
  ansible.builtin.set_fact:
    nics: "{{nic_address.results[0].json.Members}}"

- debug:
    msg: "{{nics}}"  

- name: Ethernet Interfaces list
  ansible.builtin.set_fact:
    macs: "{{macs + [item['@odata.id']]}}"
  with_items: "{{nics}}"  

- debug:
    msg: "{{macs}}"    

- name: setfacts
  ansible.builtin.set_fact:
    EI_id: "{{ EI_id + [item.split('/')[-1]]  }}"   
  with_items: "{{macs}}"

- debug:
    msg: "{{EI_id}}"    

- import_tasks: poweredge_get_macaddress.yml   
